services:
  db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
    ports:
      - "3306:3306"

  app:
    image: your_spring_boot_image
    container_name: spring-boot-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/your_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: your_password
    ports:
      - "8080:8080"
    depends_on:
      - db
